spring.application.name=wms-backend
server.servlet.context-path=/api

# Настройки БД
spring.datasource.url=jdbc:postgresql://localhost:5432/wms_system
spring.datasource.username=postgres
spring.datasource.password=1111

# Настройки JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

